# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('data1', models.IntegerField(null=True)),
                ('data2', models.IntegerField(null=True)),
                ('data3', models.IntegerField(null=True)),
                ('message_id', models.IntegerField(null=True)),
                ('network', models.IntegerField(null=True)),
                ('node_id', models.IntegerField(null=True)),
                ('ram', models.IntegerField(null=True)),
                ('recieved_at', models.DateTimeField(auto_now_add=True)),
                ('record_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(null=True)),
            ],
        ),
    ]
