# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ('id',)},
        ),
    ]
