# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0002_auto_20180206_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='data3',
        ),
    ]
