# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0004_auto_20180215_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='data_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
