# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0006_auto_20180301_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='longitude',
        ),
    ]
