# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0008_auto_20180301_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='data',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
