# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0009_auto_20180301_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
