# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0013_auto_20180509_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='net',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
