# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0016_data_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='net',
        ),
        migrations.RemoveField(
            model_name='data',
            name='ver',
        ),
    ]
