# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0017_auto_20180514_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 14, 15, 44, 12, 645178, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
