# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0018_data_received_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('-received_at',)},
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.CharField(default='HPM', max_length=10),
            preserve_default=False,
        ),
    ]
