# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 16:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0019_auto_20180514_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='bat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hpm',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=2),
        ),
        migrations.AddField(
            model_name='data',
            name='ts',
            field=models.IntegerField(null=True),
        ),
    ]
