# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0020_auto_20180514_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bat',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
