# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0021_auto_20180514_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.RemoveField(
            model_name='data',
            name='type',
        ),
    ]
