# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-24 18:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0023_auto_20190723_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.Network')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='sensordata.Network'),
        ),
        migrations.AddField(
            model_name='nodedata',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.Node'),
        ),
    ]
